[package]
name = "rustc_codegen_spir"
description = "A compiler plugin for Rust that generates SPIR-V code"
license = "MIT"
version = "0.0.0"
edition = "2021"

[dependencies]

[package.metadata.rust-analyzer]
rustc_private=true